// Food Database Module
// This file contains the comprehensive food database used by StepI
// Extracted from the original StepI.tsx to reduce bundle size

export type FoodItem = {
    name: string;
    baseEnergy: number;
    baseProtein: number;
    baseFat: number;
    baseCarbs: number;
    baseFiber: number;
    baseB12: number;
    baseZinc: number;
    region?: string; // State/Region identifier
    category?: string; // Food category
};

export const INDIAN_STATES = [
    { value: 'all', label: 'All Regions' },
    { value: 'andhra-pradesh', label: 'Andhra Pradesh' },
    { value: 'assam', label: 'Assam' },
    { value: 'bengal', label: 'West Bengal' },
    { value: 'bihar', label: 'Bihar' },
    { value: 'goa', label: 'Goa' },
    { value: 'gujarat', label: 'Gujarat' },
    { value: 'haryana', label: 'Haryana' },
    { value: 'himachal-pradesh', label: 'Himachal Pradesh' },
    { value: 'jammu-kashmir', label: 'Jammu & Kashmir' },
    { value: 'jharkhand', label: 'Jharkhand' },
    { value: 'karnataka', label: 'Karnataka' },
    { value: 'kerala', label: 'Kerala' },
    { value: 'madhya-pradesh', label: 'Madhya Pradesh' },
    { value: 'maharashtra', label: 'Maharashtra' },
    { value: 'manipur', label: 'Manipur' },
    { value: 'meghalaya', label: 'Meghalaya' },
    { value: 'mizoram', label: 'Mizoram' },
    { value: 'nagaland', label: 'Nagaland' },
    { value: 'odisha', label: 'Odisha' },
    { value: 'punjab', label: 'Punjab' },
    { value: 'rajasthan', label: 'Rajasthan' },
    { value: 'tamil-nadu', label: 'Tamil Nadu' },
    { value: 'telangana', label: 'Telangana' },
    { value: 'tripura', label: 'Tripura' },
    { value: 'uttar-pradesh', label: 'Uttar Pradesh' },
    { value: 'uttarakhand', label: 'Uttarakhand' },
];

export const foodDatabase: FoodItem[] = [
    // Common/Pan-India Foods
    { name: 'Roti/Chapathi', baseEnergy: 85, baseProtein: 3, baseFat: 0.5, baseCarbs: 18, baseFiber: 2, baseB12: 0, baseZinc: 0.5, category: 'Staple' },
    { name: 'Rice (cooked)', baseEnergy: 130, baseProtein: 2.7, baseFat: 0.3, baseCarbs: 28, baseFiber: 0.4, baseB12: 0, baseZinc: 0.6, category: 'Staple' },
    { name: 'Dal (lentil soup)', baseEnergy: 110, baseProtein: 7, baseFat: 3, baseCarbs: 15, baseFiber: 5, baseB12: 0, baseZinc: 1, category: 'Protein' },
    { name: 'Mixed Vegetable Curry', baseEnergy: 120, baseProtein: 3, baseFat: 8, baseCarbs: 10, baseFiber: 4, baseB12: 0, baseZinc: 0.8, category: 'Vegetable' },
    { name: 'Chicken Curry', baseEnergy: 220, baseProtein: 20, baseFat: 14, baseCarbs: 5, baseFiber: 1, baseB12: 0.5, baseZinc: 2.5, category: 'Protein' },
    { name: 'Milk', baseEnergy: 60, baseProtein: 3.3, baseFat: 3.3, baseCarbs: 4.8, baseFiber: 0, baseB12: 0.4, baseZinc: 0.4, category: 'Dairy' },
    { name: 'Apple', baseEnergy: 52, baseProtein: 0.3, baseFat: 0.2, baseCarbs: 14, baseFiber: 2.4, baseB12: 0, baseZinc: 0.04, category: 'Fruit' },
    { name: 'Banana', baseEnergy: 89, baseProtein: 1.1, baseFat: 0.3, baseCarbs: 23, baseFiber: 2.6, baseB12: 0, baseZinc: 0.15, category: 'Fruit' },
    { name: 'Tea with sugar', baseEnergy: 40, baseProtein: 0.5, baseFat: 0.2, baseCarbs: 9, baseFiber: 0, baseB12: 0, baseZinc: 0, category: 'Beverage' },
    { name: 'Egg (boiled)', baseEnergy: 78, baseProtein: 6, baseFat: 5, baseCarbs: 0.6, baseFiber: 0, baseB12: 0.6, baseZinc: 0.5, category: 'Protein' },
    { name: 'Spinach (cooked)', baseEnergy: 23, baseProtein: 3, baseFat: 0.3, baseCarbs: 3.6, baseFiber: 2.2, baseB12: 0, baseZinc: 0.5, category: 'Vegetable' },
    { name: 'Curd', baseEnergy: 61, baseProtein: 3.5, baseFat: 3.5, baseCarbs: 4, baseFiber: 0, baseB12: 0.4, baseZinc: 0.4, category: 'Dairy' },
    { name: 'Paneer', baseEnergy: 265, baseProtein: 18, baseFat: 20, baseCarbs: 6, baseFiber: 0, baseB12: 0.5, baseZinc: 1.2, category: 'Dairy' },

    // Andhra Pradesh Specialties (Extensive List)
    { name: 'Gongura Pachadi', baseEnergy: 150, baseProtein: 2, baseFat: 12, baseCarbs: 8, baseFiber: 3, baseB12: 0, baseZinc: 0.4, region: 'andhra-pradesh', category: 'Condiment' },
    { name: 'Pesarattu', baseEnergy: 180, baseProtein: 8, baseFat: 4, baseCarbs: 28, baseFiber: 4, baseB12: 0, baseZinc: 1.0, region: 'andhra-pradesh', category: 'Staple' },
    { name: 'Andhra Chicken Curry (Kodi Kura)', baseEnergy: 280, baseProtein: 25, baseFat: 18, baseCarbs: 6, baseFiber: 1, baseB12: 0.8, baseZinc: 2.8, region: 'andhra-pradesh', category: 'Protein' },
    { name: 'Gutti Vankaya Kura (Stuffed Brinjal)', baseEnergy: 160, baseProtein: 3, baseFat: 10, baseCarbs: 14, baseFiber: 6, baseB12: 0, baseZinc: 0.5, region: 'andhra-pradesh', category: 'Vegetable' },
    { name: 'Ulava Charu (Horsegram Soup)', baseEnergy: 90, baseProtein: 4, baseFat: 2, baseCarbs: 14, baseFiber: 3, baseB12: 0, baseZinc: 0.8, region: 'andhra-pradesh', category: 'Soup' },
    { name: 'Pootharekulu (Paper Sweet)', baseEnergy: 220, baseProtein: 2, baseFat: 8, baseCarbs: 35, baseFiber: 0, baseB12: 0, baseZinc: 0.2, region: 'andhra-pradesh', category: 'Dessert' },
    { name: 'Bobbatlu/Puran Poli', baseEnergy: 280, baseProtein: 6, baseFat: 8, baseCarbs: 45, baseFiber: 3, baseB12: 0, baseZinc: 0.6, region: 'andhra-pradesh', category: 'Dessert' },
    { name: 'Ariselu', baseEnergy: 300, baseProtein: 3, baseFat: 12, baseCarbs: 45, baseFiber: 1, baseB12: 0, baseZinc: 0.4, region: 'andhra-pradesh', category: 'Dessert' },
    { name: 'Royyala Iguru (Prawn Curry)', baseEnergy: 240, baseProtein: 22, baseFat: 14, baseCarbs: 4, baseFiber: 0, baseB12: 1.5, baseZinc: 2.0, region: 'andhra-pradesh', category: 'Protein' },
    { name: 'Chepala Pulusu (Fish Stew)', baseEnergy: 180, baseProtein: 20, baseFat: 8, baseCarbs: 6, baseFiber: 1, baseB12: 2.2, baseZinc: 1.0, region: 'andhra-pradesh', category: 'Protein' },
    { name: 'Punugulu', baseEnergy: 250, baseProtein: 5, baseFat: 12, baseCarbs: 30, baseFiber: 2, baseB12: 0, baseZinc: 0.5, region: 'andhra-pradesh', category: 'Snack' },
    { name: 'Mirchi Bajji', baseEnergy: 200, baseProtein: 4, baseFat: 12, baseCarbs: 18, baseFiber: 2, baseB12: 0, baseZinc: 0.4, region: 'andhra-pradesh', category: 'Snack' },
    { name: 'Ragi Sangati', baseEnergy: 160, baseProtein: 4, baseFat: 1, baseCarbs: 34, baseFiber: 4, baseB12: 0, baseZinc: 1.2, region: 'andhra-pradesh', category: 'Staple' },
    { name: 'Natukodi Pulusu (Country Chicken)', baseEnergy: 260, baseProtein: 24, baseFat: 16, baseCarbs: 5, baseFiber: 1, baseB12: 0.6, baseZinc: 3.0, region: 'andhra-pradesh', category: 'Protein' },
    { name: 'Kanda Bachali Kura (Yam & Spinach)', baseEnergy: 140, baseProtein: 3, baseFat: 5, baseCarbs: 20, baseFiber: 5, baseB12: 0, baseZinc: 0.6, region: 'andhra-pradesh', category: 'Vegetable' },
    { name: 'Panasa Puttu Kura (Jackfruit Curry)', baseEnergy: 150, baseProtein: 3, baseFat: 7, baseCarbs: 18, baseFiber: 6, baseB12: 0, baseZinc: 0.5, region: 'andhra-pradesh', category: 'Vegetable' },
    { name: 'Dondakaya Fry (Ivy Gourd)', baseEnergy: 160, baseProtein: 2, baseFat: 10, baseCarbs: 14, baseFiber: 3, baseB12: 0, baseZinc: 0.4, region: 'andhra-pradesh', category: 'Vegetable' },
    { name: 'Bendakaya Pulusu (Okra Stew)', baseEnergy: 110, baseProtein: 2, baseFat: 4, baseCarbs: 16, baseFiber: 4, baseB12: 0, baseZinc: 0.5, region: 'andhra-pradesh', category: 'Vegetable' },
    { name: 'Mamidikaya Pappu (Mango Dal)', baseEnergy: 160, baseProtein: 8, baseFat: 4, baseCarbs: 22, baseFiber: 5, baseB12: 0, baseZinc: 1.0, region: 'andhra-pradesh', category: 'Protein' },
    { name: 'Dosakaya Pappu (Cucumber Dal)', baseEnergy: 150, baseProtein: 8, baseFat: 4, baseCarbs: 20, baseFiber: 5, baseB12: 0, baseZinc: 1.0, region: 'andhra-pradesh', category: 'Protein' },
    { name: 'Menthi Kura Pappu (Fenugreek Dal)', baseEnergy: 155, baseProtein: 9, baseFat: 4, baseCarbs: 20, baseFiber: 6, baseB12: 0, baseZinc: 1.1, region: 'andhra-pradesh', category: 'Protein' },
    { name: 'Gongura Mamsam (Mutton with Sorrel)', baseEnergy: 320, baseProtein: 22, baseFat: 24, baseCarbs: 4, baseFiber: 2, baseB12: 1.8, baseZinc: 4.0, region: 'andhra-pradesh', category: 'Protein' },
    { name: 'Kakinada Kaja', baseEnergy: 350, baseProtein: 3, baseFat: 15, baseCarbs: 50, baseFiber: 0, baseB12: 0, baseZinc: 0.2, region: 'andhra-pradesh', category: 'Dessert' },
    { name: 'Sunnundalu (Urad Dal Laddu)', baseEnergy: 280, baseProtein: 8, baseFat: 14, baseCarbs: 30, baseFiber: 3, baseB12: 0, baseZinc: 0.8, region: 'andhra-pradesh', category: 'Dessert' },
    { name: 'Bandar Laddu', baseEnergy: 300, baseProtein: 4, baseFat: 16, baseCarbs: 35, baseFiber: 1, baseB12: 0, baseZinc: 0.4, region: 'andhra-pradesh', category: 'Dessert' },
    { name: 'Gavvalu', baseEnergy: 320, baseProtein: 4, baseFat: 12, baseCarbs: 48, baseFiber: 1, baseB12: 0, baseZinc: 0.3, region: 'andhra-pradesh', category: 'Snack' },
    { name: 'Chekkalu (Rice Crackers)', baseEnergy: 220, baseProtein: 3, baseFat: 10, baseCarbs: 30, baseFiber: 1, baseB12: 0, baseZinc: 0.4, region: 'andhra-pradesh', category: 'Snack' },
    { name: 'Sakinalu', baseEnergy: 200, baseProtein: 3, baseFat: 8, baseCarbs: 28, baseFiber: 1, baseB12: 0, baseZinc: 0.3, region: 'andhra-pradesh', category: 'Snack' },
    { name: 'Alasanda Vada (Black-eyed Pea Fritter)', baseEnergy: 180, baseProtein: 7, baseFat: 8, baseCarbs: 20, baseFiber: 4, baseB12: 0, baseZinc: 0.9, region: 'andhra-pradesh', category: 'Snack' },
    { name: 'Perugu Vada (Curd Vada)', baseEnergy: 200, baseProtein: 6, baseFat: 8, baseCarbs: 24, baseFiber: 2, baseB12: 0.3, baseZinc: 0.6, region: 'andhra-pradesh', category: 'Snack' },
    { name: 'Upma Pesarattu', baseEnergy: 350, baseProtein: 10, baseFat: 12, baseCarbs: 50, baseFiber: 5, baseB12: 0, baseZinc: 1.2, region: 'andhra-pradesh', category: 'Meal' },
    { name: 'Pulihora (Tamarind Rice)', baseEnergy: 280, baseProtein: 4, baseFat: 10, baseCarbs: 45, baseFiber: 2, baseB12: 0, baseZinc: 0.5, region: 'andhra-pradesh', category: 'Staple' },
    { name: 'Daddojanam (Curd Rice)', baseEnergy: 220, baseProtein: 6, baseFat: 8, baseCarbs: 30, baseFiber: 1, baseB12: 0.4, baseZinc: 0.5, region: 'andhra-pradesh', category: 'Staple' },
    { name: 'Kobbari Annam (Coconut Rice)', baseEnergy: 320, baseProtein: 5, baseFat: 16, baseCarbs: 38, baseFiber: 3, baseB12: 0, baseZinc: 0.6, region: 'andhra-pradesh', category: 'Staple' },
    { name: 'Karivepaku Podi (Curry Leaf Powder)', baseEnergy: 40, baseProtein: 2, baseFat: 2, baseCarbs: 4, baseFiber: 2, baseB12: 0, baseZinc: 0.3, region: 'andhra-pradesh', category: 'Condiment' },
    { name: 'Nalla Karam Podi', baseEnergy: 45, baseProtein: 2, baseFat: 2, baseCarbs: 5, baseFiber: 2, baseB12: 0, baseZinc: 0.3, region: 'andhra-pradesh', category: 'Condiment' },
    { name: 'Kandi Podi (Gunpowder)', baseEnergy: 50, baseProtein: 3, baseFat: 2, baseCarbs: 5, baseFiber: 2, baseB12: 0, baseZinc: 0.4, region: 'andhra-pradesh', category: 'Condiment' },
    { name: 'Avakaya (Mango Pickle)', baseEnergy: 60, baseProtein: 0.5, baseFat: 5, baseCarbs: 4, baseFiber: 1, baseB12: 0, baseZinc: 0.1, region: 'andhra-pradesh', category: 'Condiment' },
    { name: 'Tomato Pachadi', baseEnergy: 40, baseProtein: 1, baseFat: 3, baseCarbs: 4, baseFiber: 1, baseB12: 0, baseZinc: 0.2, region: 'andhra-pradesh', category: 'Condiment' },
    { name: 'Allam Pachadi (Ginger Pickle)', baseEnergy: 50, baseProtein: 0.5, baseFat: 3, baseCarbs: 6, baseFiber: 1, baseB12: 0, baseZinc: 0.2, region: 'andhra-pradesh', category: 'Condiment' },
    { name: 'Beerakaya Pachadi (Ridge Gourd)', baseEnergy: 60, baseProtein: 1, baseFat: 4, baseCarbs: 5, baseFiber: 2, baseB12: 0, baseZinc: 0.3, region: 'andhra-pradesh', category: 'Condiment' },
    { name: 'Gongura Chicken', baseEnergy: 260, baseProtein: 22, baseFat: 16, baseCarbs: 4, baseFiber: 2, baseB12: 0.6, baseZinc: 2.6, region: 'andhra-pradesh', category: 'Protein' },
    { name: 'Bommidayala Pulusu', baseEnergy: 190, baseProtein: 18, baseFat: 10, baseCarbs: 6, baseFiber: 1, baseB12: 1.8, baseZinc: 1.2, region: 'andhra-pradesh', category: 'Protein' },
    { name: 'Crab Curry (Peethala Iguru)', baseEnergy: 160, baseProtein: 18, baseFat: 6, baseCarbs: 4, baseFiber: 0, baseB12: 3.0, baseZinc: 3.5, region: 'andhra-pradesh', category: 'Protein' },
    { name: 'Liver Fry', baseEnergy: 220, baseProtein: 24, baseFat: 10, baseCarbs: 4, baseFiber: 0, baseB12: 15.0, baseZinc: 4.0, region: 'andhra-pradesh', category: 'Protein' },
    { name: 'Boti Curry', baseEnergy: 240, baseProtein: 20, baseFat: 16, baseCarbs: 2, baseFiber: 0, baseB12: 2.0, baseZinc: 3.0, region: 'andhra-pradesh', category: 'Protein' },
    { name: 'Talakaya Kura (Head Meat Curry)', baseEnergy: 280, baseProtein: 22, baseFat: 20, baseCarbs: 2, baseFiber: 0, baseB12: 2.5, baseZinc: 3.5, region: 'andhra-pradesh', category: 'Protein' },
    { name: 'Chintachiguru Pappu', baseEnergy: 150, baseProtein: 8, baseFat: 4, baseCarbs: 20, baseFiber: 6, baseB12: 0, baseZinc: 1.0, region: 'andhra-pradesh', category: 'Protein' },
    { name: 'Mullangi Sambar (Radish)', baseEnergy: 90, baseProtein: 4, baseFat: 3, baseCarbs: 12, baseFiber: 3, baseB12: 0, baseZinc: 0.5, region: 'andhra-pradesh', category: 'Soup' },
    { name: 'Majiga Pulusu (Buttermilk Stew)', baseEnergy: 80, baseProtein: 3, baseFat: 4, baseCarbs: 8, baseFiber: 0, baseB12: 0.3, baseZinc: 0.4, region: 'andhra-pradesh', category: 'Soup' },

    // North Indian - Punjab, Haryana, Delhi, UP
    { name: 'Paratha', baseEnergy: 150, baseProtein: 4, baseFat: 6, baseCarbs: 22, baseFiber: 2, baseB12: 0, baseZinc: 0.5, region: 'punjab', category: 'Staple' },
    { name: 'Aloo Paratha', baseEnergy: 180, baseProtein: 4, baseFat: 8, baseCarbs: 25, baseFiber: 2.5, baseB12: 0, baseZinc: 0.6, region: 'punjab', category: 'Staple' },
    { name: 'Makki di Roti', baseEnergy: 120, baseProtein: 3.5, baseFat: 2, baseCarbs: 22, baseFiber: 3, baseB12: 0, baseZinc: 0.8, region: 'punjab', category: 'Staple' },
    { name: 'Sarson da Saag', baseEnergy: 90, baseProtein: 4, baseFat: 5, baseCarbs: 8, baseFiber: 3, baseB12: 0, baseZinc: 0.7, region: 'punjab', category: 'Vegetable' },
    { name: 'Rajma', baseEnergy: 140, baseProtein: 9, baseFat: 1, baseCarbs: 23, baseFiber: 7, baseB12: 0, baseZinc: 1.0, region: 'punjab', category: 'Protein' },
    { name: 'Chana Masala', baseEnergy: 180, baseProtein: 8, baseFat: 6, baseCarbs: 26, baseFiber: 6, baseB12: 0, baseZinc: 1.5, region: 'punjab', category: 'Protein' },
    { name: 'Lassi', baseEnergy: 150, baseProtein: 6, baseFat: 6, baseCarbs: 16, baseFiber: 0, baseB12: 0.4, baseZinc: 0.5, region: 'punjab', category: 'Beverage' },
    { name: 'Chole Bhature', baseEnergy: 450, baseProtein: 12, baseFat: 20, baseCarbs: 55, baseFiber: 8, baseB12: 0, baseZinc: 2.0, region: 'punjab', category: 'Meal' },
    { name: 'Kadhi Pakora', baseEnergy: 180, baseProtein: 6, baseFat: 10, baseCarbs: 18, baseFiber: 2, baseB12: 0.3, baseZinc: 0.8, region: 'punjab', category: 'Curry' },
    { name: 'Butter Chicken', baseEnergy: 350, baseProtein: 22, baseFat: 25, baseCarbs: 8, baseFiber: 1, baseB12: 0.6, baseZinc: 2.0, region: 'punjab', category: 'Protein' },
    { name: 'Dal Makhani', baseEnergy: 280, baseProtein: 10, baseFat: 18, baseCarbs: 20, baseFiber: 6, baseB12: 0.2, baseZinc: 1.2, region: 'punjab', category: 'Protein' },
    { name: 'Paneer Tikka', baseEnergy: 220, baseProtein: 16, baseFat: 14, baseCarbs: 6, baseFiber: 1, baseB12: 0.4, baseZinc: 1.0, region: 'punjab', category: 'Snack' },
    { name: 'Malai Kofta', baseEnergy: 320, baseProtein: 8, baseFat: 22, baseCarbs: 24, baseFiber: 3, baseB12: 0.3, baseZinc: 0.8, region: 'punjab', category: 'Curry' },
    { name: 'Baingan Bharta', baseEnergy: 140, baseProtein: 3, baseFat: 8, baseCarbs: 14, baseFiber: 6, baseB12: 0, baseZinc: 0.5, region: 'punjab', category: 'Vegetable' },

    // South Indian - Tamil Nadu, Karnataka, Kerala
    { name: 'Idli', baseEnergy: 60, baseProtein: 2, baseFat: 0.4, baseCarbs: 13, baseFiber: 0.5, baseB12: 0, baseZinc: 0.2, region: 'tamil-nadu', category: 'Staple' },
    { name: 'Dosa', baseEnergy: 130, baseProtein: 3, baseFat: 6, baseCarbs: 18, baseFiber: 1, baseB12: 0, baseZinc: 0.3, region: 'tamil-nadu', category: 'Staple' },
    { name: 'Sambar', baseEnergy: 80, baseProtein: 4, baseFat: 3, baseCarbs: 10, baseFiber: 2, baseB12: 0, baseZinc: 0.4, region: 'tamil-nadu', category: 'Curry' },
    { name: 'Coconut Chutney', baseEnergy: 80, baseProtein: 2, baseFat: 6, baseCarbs: 6, baseFiber: 2, baseB12: 0, baseZinc: 0.3, region: 'tamil-nadu', category: 'Condiment' },
    { name: 'Vada', baseEnergy: 150, baseProtein: 5, baseFat: 8, baseCarbs: 16, baseFiber: 2, baseB12: 0, baseZinc: 0.6, region: 'tamil-nadu', category: 'Snack' },
    { name: 'Upma', baseEnergy: 200, baseProtein: 5, baseFat: 8, baseCarbs: 28, baseFiber: 2, baseB12: 0, baseZinc: 0.5, region: 'karnataka', category: 'Staple' },
    { name: 'Bisi Bele Bath', baseEnergy: 220, baseProtein: 6, baseFat: 8, baseCarbs: 32, baseFiber: 4, baseB12: 0, baseZinc: 1.0, region: 'karnataka', category: 'Meal' },
    { name: 'Rasam', baseEnergy: 50, baseProtein: 2, baseFat: 2, baseCarbs: 8, baseFiber: 1, baseB12: 0, baseZinc: 0.3, region: 'tamil-nadu', category: 'Soup' },
    { name: 'Pongal', baseEnergy: 180, baseProtein: 5, baseFat: 6, baseCarbs: 26, baseFiber: 2, baseB12: 0, baseZinc: 0.7, region: 'tamil-nadu', category: 'Staple' },
    { name: 'Appam', baseEnergy: 120, baseProtein: 2, baseFat: 2, baseCarbs: 24, baseFiber: 1, baseB12: 0, baseZinc: 0.3, region: 'kerala', category: 'Staple' },
    { name: 'Puttu', baseEnergy: 140, baseProtein: 3, baseFat: 1, baseCarbs: 30, baseFiber: 2, baseB12: 0, baseZinc: 0.4, region: 'kerala', category: 'Staple' },
    { name: 'Fish Curry (Kerala)', baseEnergy: 180, baseProtein: 20, baseFat: 8, baseCarbs: 2, baseFiber: 1, baseB12: 2.0, baseZinc: 1.0, region: 'kerala', category: 'Protein' },
    { name: 'Avial', baseEnergy: 100, baseProtein: 3, baseFat: 6, baseCarbs: 10, baseFiber: 3, baseB12: 0, baseZinc: 0.5, region: 'kerala', category: 'Vegetable' },
    { name: 'Hyderabadi Biryani', baseEnergy: 350, baseProtein: 15, baseFat: 12, baseCarbs: 45, baseFiber: 3, baseB12: 0.5, baseZinc: 2.5, region: 'telangana', category: 'Meal' },
    { name: 'Mysore Pak', baseEnergy: 380, baseProtein: 2, baseFat: 22, baseCarbs: 40, baseFiber: 0, baseB12: 0, baseZinc: 0.2, region: 'karnataka', category: 'Dessert' },
    { name: 'Payasam', baseEnergy: 250, baseProtein: 4, baseFat: 8, baseCarbs: 40, baseFiber: 0.5, baseB12: 0.3, baseZinc: 0.4, region: 'tamil-nadu', category: 'Dessert' },

    // West Indian - Maharashtra, Gujarat, Goa
    { name: 'Poha', baseEnergy: 180, baseProtein: 4, baseFat: 6, baseCarbs: 30, baseFiber: 2, baseB12: 0, baseZinc: 0.5, region: 'maharashtra', category: 'Staple' },
    { name: 'Misal Pav', baseEnergy: 300, baseProtein: 10, baseFat: 12, baseCarbs: 40, baseFiber: 6, baseB12: 0, baseZinc: 1.5, region: 'maharashtra', category: 'Meal' },
    { name: 'Vada Pav', baseEnergy: 250, baseProtein: 6, baseFat: 10, baseCarbs: 35, baseFiber: 3, baseB12: 0, baseZinc: 0.8, region: 'maharashtra', category: 'Snack' },
    { name: 'Pav Bhaji', baseEnergy: 280, baseProtein: 7, baseFat: 12, baseCarbs: 38, baseFiber: 4, baseB12: 0, baseZinc: 1.0, region: 'maharashtra', category: 'Meal' },
    { name: 'Dhokla', baseEnergy: 160, baseProtein: 5, baseFat: 4, baseCarbs: 28, baseFiber: 2, baseB12: 0, baseZinc: 0.6, region: 'gujarat', category: 'Snack' },
    { name: 'Khandvi', baseEnergy: 120, baseProtein: 4, baseFat: 6, baseCarbs: 14, baseFiber: 1, baseB12: 0, baseZinc: 0.5, region: 'gujarat', category: 'Snack' },
    { name: 'Thepla', baseEnergy: 140, baseProtein: 4, baseFat: 5, baseCarbs: 20, baseFiber: 2.5, baseB12: 0, baseZinc: 0.6, region: 'gujarat', category: 'Staple' },
    { name: 'Undhiyu', baseEnergy: 180, baseProtein: 5, baseFat: 8, baseCarbs: 22, baseFiber: 5, baseB12: 0, baseZinc: 1.0, region: 'gujarat', category: 'Vegetable' },
    { name: 'Fish Curry (Goan)', baseEnergy: 200, baseProtein: 22, baseFat: 10, baseCarbs: 3, baseFiber: 1, baseB12: 2.5, baseZinc: 1.2, region: 'goa', category: 'Protein' },
    { name: 'Vindaloo', baseEnergy: 280, baseProtein: 18, baseFat: 18, baseCarbs: 8, baseFiber: 2, baseB12: 1.0, baseZinc: 2.0, region: 'goa', category: 'Curry' },
    { name: 'Sabudana Khichdi', baseEnergy: 250, baseProtein: 2, baseFat: 10, baseCarbs: 45, baseFiber: 1, baseB12: 0, baseZinc: 0.3, region: 'maharashtra', category: 'Staple' },
    { name: 'Puran Poli', baseEnergy: 280, baseProtein: 6, baseFat: 8, baseCarbs: 45, baseFiber: 3, baseB12: 0, baseZinc: 0.6, region: 'maharashtra', category: 'Dessert' },
    { name: 'Shrikhand', baseEnergy: 260, baseProtein: 6, baseFat: 10, baseCarbs: 35, baseFiber: 0, baseB12: 0.4, baseZinc: 0.5, region: 'maharashtra', category: 'Dessert' },

    // East Indian - West Bengal, Odisha, Assam
    { name: 'Luchi', baseEnergy: 160, baseProtein: 3, baseFat: 8, baseCarbs: 20, baseFiber: 1, baseB12: 0, baseZinc: 0.4, region: 'bengal', category: 'Staple' },
    { name: 'Machher Jhol', baseEnergy: 180, baseProtein: 20, baseFat: 8, baseCarbs: 4, baseFiber: 1, baseB12: 2.0, baseZinc: 1.0, region: 'bengal', category: 'Curry' },
    { name: 'Shukto', baseEnergy: 100, baseProtein: 3, baseFat: 6, baseCarbs: 10, baseFiber: 3, baseB12: 0, baseZinc: 0.5, region: 'bengal', category: 'Vegetable' },
    { name: 'Mishti Doi', baseEnergy: 150, baseProtein: 5, baseFat: 6, baseCarbs: 20, baseFiber: 0, baseB12: 0.5, baseZinc: 0.6, region: 'bengal', category: 'Dessert' },
    { name: 'Pakhala', baseEnergy: 120, baseProtein: 3, baseFat: 1, baseCarbs: 25, baseFiber: 1, baseB12: 0, baseZinc: 0.5, region: 'odisha', category: 'Staple' },
    { name: 'Dalma', baseEnergy: 140, baseProtein: 7, baseFat: 4, baseCarbs: 20, baseFiber: 5, baseB12: 0, baseZinc: 1.0, region: 'odisha', category: 'Curry' },
    { name: 'Khichdi (Assamese)', baseEnergy: 180, baseProtein: 6, baseFat: 4, baseCarbs: 30, baseFiber: 3, baseB12: 0, baseZinc: 0.8, region: 'assam', category: 'Meal' },
    { name: 'Pitha', baseEnergy: 200, baseProtein: 4, baseFat: 6, baseCarbs: 32, baseFiber: 2, baseB12: 0, baseZinc: 0.6, region: 'assam', category: 'Snack' },
    { name: 'Rasgulla', baseEnergy: 140, baseProtein: 3, baseFat: 1, baseCarbs: 30, baseFiber: 0, baseB12: 0.1, baseZinc: 0.2, region: 'bengal', category: 'Dessert' },
    { name: 'Sandesh', baseEnergy: 120, baseProtein: 4, baseFat: 4, baseCarbs: 18, baseFiber: 0, baseB12: 0.2, baseZinc: 0.3, region: 'bengal', category: 'Dessert' },
    { name: 'Chingri Malai Curry', baseEnergy: 280, baseProtein: 18, baseFat: 20, baseCarbs: 6, baseFiber: 1, baseB12: 1.5, baseZinc: 1.8, region: 'bengal', category: 'Protein' },

    // Rajasthan
    { name: 'Dal Baati Churma', baseEnergy: 400, baseProtein: 10, baseFat: 15, baseCarbs: 55, baseFiber: 6, baseB12: 0, baseZinc: 1.5, region: 'rajasthan', category: 'Meal' },
    { name: 'Gatte ki Sabzi', baseEnergy: 180, baseProtein: 6, baseFat: 8, baseCarbs: 22, baseFiber: 3, baseB12: 0, baseZinc: 0.8, region: 'rajasthan', category: 'Curry' },
    { name: 'Ker Sangri', baseEnergy: 120, baseProtein: 4, baseFat: 6, baseCarbs: 14, baseFiber: 4, baseB12: 0, baseZinc: 0.7, region: 'rajasthan', category: 'Vegetable' },
    { name: 'Laal Maas', baseEnergy: 320, baseProtein: 24, baseFat: 22, baseCarbs: 4, baseFiber: 1, baseB12: 2.0, baseZinc: 3.5, region: 'rajasthan', category: 'Protein' },
    { name: 'Ghevar', baseEnergy: 400, baseProtein: 4, baseFat: 20, baseCarbs: 50, baseFiber: 1, baseB12: 0, baseZinc: 0.4, region: 'rajasthan', category: 'Dessert' },

    // Common Snacks & Others
    { name: 'Aloo Sabzi', baseEnergy: 120, baseProtein: 2, baseFat: 6, baseCarbs: 15, baseFiber: 3, baseB12: 0, baseZinc: 0.3, category: 'Vegetable' },
    { name: 'Bhindi Fry', baseEnergy: 130, baseProtein: 2, baseFat: 9, baseCarbs: 9, baseFiber: 3, baseB12: 0, baseZinc: 0.4, category: 'Vegetable' },
    { name: 'Mutton Curry', baseEnergy: 250, baseProtein: 20, baseFat: 16, baseCarbs: 3, baseFiber: 1, baseB12: 1.5, baseZinc: 3.5, category: 'Protein' },
    { name: 'Egg Omelette', baseEnergy: 150, baseProtein: 9, baseFat: 12, baseCarbs: 1, baseFiber: 0, baseB12: 0.6, baseZinc: 1.0, category: 'Protein' },
    { name: 'Bread Slice', baseEnergy: 70, baseProtein: 2.5, baseFat: 1, baseCarbs: 13, baseFiber: 0.8, baseB12: 0, baseZinc: 0.2, category: 'Staple' },
    { name: 'Butter', baseEnergy: 102, baseProtein: 0.1, baseFat: 11.5, baseCarbs: 0, baseFiber: 0, baseB12: 0, baseZinc: 0, category: 'Condiment' },
    { name: 'Orange', baseEnergy: 47, baseProtein: 0.9, baseFat: 0.1, baseCarbs: 12, baseFiber: 2.4, baseB12: 0, baseZinc: 0.1, category: 'Fruit' },
    { name: 'Mango', baseEnergy: 60, baseProtein: 0.8, baseFat: 0.4, baseCarbs: 15, baseFiber: 1.6, baseB12: 0, baseZinc: 0.1, category: 'Fruit' },
    { name: 'Papaya', baseEnergy: 43, baseProtein: 0.5, baseFat: 0.3, baseCarbs: 11, baseFiber: 1.7, baseB12: 0, baseZinc: 0.1, category: 'Fruit' },
    { name: 'Cucumber', baseEnergy: 16, baseProtein: 0.7, baseFat: 0.1, baseCarbs: 3.8, baseFiber: 0.5, baseB12: 0, baseZinc: 0.1, category: 'Vegetable' },
    { name: 'Tomato', baseEnergy: 18, baseProtein: 0.9, baseFat: 0.2, baseCarbs: 3.9, baseFiber: 1.2, baseB12: 0, baseZinc: 0.1, category: 'Vegetable' },
    { name: 'Coffee', baseEnergy: 2, baseProtein: 0.3, baseFat: 0, baseCarbs: 0, baseFiber: 0, baseB12: 0, baseZinc: 0, category: 'Beverage' },
    { name: 'Green Tea', baseEnergy: 0, baseProtein: 0, baseFat: 0, baseCarbs: 0, baseFiber: 0, baseB12: 0, baseZinc: 0, category: 'Beverage' },
    { name: 'Biscuits', baseEnergy: 450, baseProtein: 6, baseFat: 18, baseCarbs: 65, baseFiber: 2, baseB12: 0, baseZinc: 0.5, category: 'Snack' },
    { name: 'Namkeen', baseEnergy: 500, baseProtein: 10, baseFat: 30, baseCarbs: 50, baseFiber: 5, baseB12: 0, baseZinc: 1.5, category: 'Snack' },
    { name: 'Chocolate', baseEnergy: 546, baseProtein: 5, baseFat: 31, baseCarbs: 61, baseFiber: 7, baseB12: 0, baseZinc: 2.3, category: 'Snack' },
    { name: 'Ice Cream', baseEnergy: 207, baseProtein: 3.5, baseFat: 11, baseCarbs: 24, baseFiber: 0.7, baseB12: 0.3, baseZinc: 0.7, category: 'Dessert' },
    { name: 'Pizza', baseEnergy: 266, baseProtein: 11, baseFat: 10, baseCarbs: 33, baseFiber: 2.5, baseB12: 0.3, baseZinc: 1.5, category: 'Fast Food' },
    { name: 'Burger', baseEnergy: 295, baseProtein: 17, baseFat: 14, baseCarbs: 24, baseFiber: 1.5, baseB12: 1.2, baseZinc: 2.5, category: 'Fast Food' },
    { name: 'French Fries', baseEnergy: 312, baseProtein: 3.4, baseFat: 15, baseCarbs: 41, baseFiber: 3.8, baseB12: 0, baseZinc: 0.4, category: 'Fast Food' },
    { name: 'Pasta', baseEnergy: 131, baseProtein: 5, baseFat: 1.1, baseCarbs: 25, baseFiber: 1.8, baseB12: 0, baseZinc: 0.5, category: 'Fast Food' },
    { name: 'Noodles', baseEnergy: 138, baseProtein: 4.5, baseFat: 2.1, baseCarbs: 25, baseFiber: 1.2, baseB12: 0, baseZinc: 0.4, category: 'Fast Food' },
    { name: 'Sandwich', baseEnergy: 250, baseProtein: 9, baseFat: 10, baseCarbs: 30, baseFiber: 3, baseB12: 0.2, baseZinc: 1.2, category: 'Snack' },
    { name: 'Salad', baseEnergy: 50, baseProtein: 2, baseFat: 2, baseCarbs: 8, baseFiber: 3, baseB12: 0, baseZinc: 0.3, category: 'Vegetable' },
    { name: 'Soup', baseEnergy: 60, baseProtein: 3, baseFat: 2, baseCarbs: 8, baseFiber: 1.5, baseB12: 0, baseZinc: 0.4, category: 'Soup' },
    { name: 'Samosa', baseEnergy: 260, baseProtein: 4, baseFat: 14, baseCarbs: 30, baseFiber: 2, baseB12: 0, baseZinc: 0.4, category: 'Snack' },
    { name: 'Pakora', baseEnergy: 200, baseProtein: 4, baseFat: 12, baseCarbs: 18, baseFiber: 2, baseB12: 0, baseZinc: 0.5, category: 'Snack' },
    { name: 'Gulab Jamun', baseEnergy: 150, baseProtein: 2, baseFat: 6, baseCarbs: 22, baseFiber: 0, baseB12: 0.1, baseZinc: 0.2, category: 'Dessert' },
    { name: 'Jalebi', baseEnergy: 150, baseProtein: 1, baseFat: 8, baseCarbs: 20, baseFiber: 0, baseB12: 0, baseZinc: 0.1, category: 'Dessert' },
    { name: 'Kheer', baseEnergy: 200, baseProtein: 5, baseFat: 8, baseCarbs: 28, baseFiber: 0.5, baseB12: 0.3, baseZinc: 0.5, category: 'Dessert' },
    { name: 'Halwa', baseEnergy: 300, baseProtein: 3, baseFat: 15, baseCarbs: 40, baseFiber: 1, baseB12: 0, baseZinc: 0.3, category: 'Dessert' }
];
